### ISSUE TITLE
Registriersystem ergänzen

### ISSUE THREAD

**Issue by Mechtecs** [Schul-O-Mat/Schul-O-Mat#3]

**Comment by jeriox** [comment]
Wir sollten da erst nochmal überlegen wie wir die Schüler verifizieren, entweder per Mail an die Schule à la: "Max Muster aus der 10b will sich registrieren, falls der bei euch ist bitte hier klicken" oder per Upload schülerausweis (datenschutzmäßig kacke) und manuelle überprüfung durch uns. Bei der Schullösung muss man die schulen halt immer erst fragen...

**Comment by leona-ya** [comment]
Die frage ist was schneller funktioniert und was die Schulen wollen?

**Comment by Mechtecs** [comment]
+1 fürs E-Mail Verfahren

**Comment by jeriox** [comment]
ich pack mich da mal dazu und frag bei meinen schulen nach

**Comment by leona-ya** [comment]
abhängig von #49, #48, #45. aka #52

**Comment by jeriox** [comment]
hier zu weil #52 das genaue verfahren beschreibt
