### ISSUE TITLE
Darstellung Filter

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#33]
Auswahl Schulart als Dropdown statt einzelner Checkboxen
Bisschen Aufhübschen :D
Feld für Ort etwas klein
Evtl. Darstellung in Spalten nebeneinander

**Comment by leona-ya** [comment]
I do it

**Comment by leona-ya** [comment]
Fixed

**Comment by Mechtecs** [comment]
jup, schulart fehlt
