### ISSUE TITLE
Bug in Password Reset

### ISSUE THREAD

**Issue by leona-ya** [Schul-O-Mat/Schul-O-Mat#36]
In Passwort zurücksetzen beim Absenden Error!
Screenshot siehe Slack #waffle-tasks

**Comment by Mechtecs** [comment]
LINKED TO https://github.com/Schul-O-Mat/Schul-O-Mat/issues/22

**Comment by leona-ya** [comment]
Server Fehler

**Comment by leona-ya** [comment]
In meiner dev funktioniert es (auch mit uber) fragen an mich

**Comment by jeriox** [comment]
zu da nicht reproduzierbar
