### ISSUE TITLE
Fragebogen Fragen ändern (für RLP)

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#43]
"Toiletten" zu Hygiene ändern
Länge der Schulstunden zu "Wie findest du die Technik an deiner Schule" ändern
Zeit des Schulbeginns ändern in "Wie kompakt ist der Stundenplan in der Oberstufe?"

**Comment by leona-ya** [comment]
Zurzeit werden die keywords nicht festgelegt deshalb funktioniert 1 noch nicht
