### ISSUE TITLE
Differenzierung der Fragen nach Bundesland

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#47]
Neue Spalte "Bundesland" in "schulen"
Neue Tabelle "fragen" mit "id", "bundesland", "frage1" etc
entsprechende verknüpfung auf der detailseite
filtern nach bundesland

**Comment by jeriox** [comment]
Müssen wir Fragen nach Bundesland differenzieren? Eigentlich ja nicht, da wir Fragen jetzt ja nach Schule differenzieren, oder? Der Rest ist ja erledigt (bis auf den Filter)

**Comment by leona-ya** [comment]
ne, brauchen wir eig nicht
