### ISSUE TITLE
Analytics-Tool einbinden

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#51]

**Comment by leona-ya** [comment]
Wollen wir das mit in der beta haben?

**Comment by leona-ya** [comment]
Ich habe eins (piwik) bei mir installiert, wofür ich dir auch einen account geben kann

**Comment by jeriox** [comment]
Was heißt denn bei dir? Hätte jetzt ehrlich gesagt bei Gelegenheit nen Google Analytics Token reingeworfen, aber Piwik wäre natürlich cooler

**Comment by leona-ya** [comment]
Das liegt auf meinem Server

**Comment by jeriox** [comment]
Kann der dann auch externe Seiten tracken? Habe noch nie Piwik aktiv benutzt

**Comment by leona-ya** [comment]
ja,  ich kann einfach ne domain reinwerfen und der schmeißt mir dann den js schnipsel raus
