### ISSUE TITLE
Kompatibilität zu Schulen außerhalb NRW

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#7]
Der erste Satz testschulen kommt jetzt ja aus RLP. Das heißt wir brauchen a) ne möglichkeit um schulen einzutragen und b) seiten zum schulprofil pflegen / aktualisieren c) müssen uns ne datenstruktur ausdenken, vor allem was die schulnummern angeht, die nicht mit den NRW-Daten kollidiert

**Comment by Mechtecs** [comment]
evtl. eine weitere relation für schulen, die eine "nrw-schul-id" haben. sonst einfach alle schulen in die schulen tabelle eintragen und id als increment

**Comment by jeriox** [comment]
nicht sonderlich sauber, können wir nicht einfach auf die nrw-id incrementen? evtl mit abstand falls da neue schulen kommen

**Comment by jeriox** [comment]
nächstes Problem: wenn wir die koordinaten eintragen, müssen wir das entweder im Gauß-Krüger-System machen (ziemlich bäh) oder in der Datenbank kennzeichnen, ob das jetzt lat und long oder rw und hw sind -> ergo ob nrw oder nicht, dann wären wir wieder bei deinem vorschlag. ist aber halt auch ein bisschen bäh...

**Comment by jeriox** [comment]
Ist mit der neuen Datenbankstruktur gefixt
