### ISSUE TITLE
View: Accountdaten ändern

### ISSUE THREAD

**Issue by leona-ya** [Schul-O-Mat/Schul-O-Mat#72]

**Comment by leona-ya** [comment]
- [x] Email Adresse
- [x] Passwort
- [x] Schule (+ SchulCode)

**Comment by jeriox** [comment]
Wenn du aber eine Möglichkeit zum Ändern von Schule & Schulcode haben willst, müssen wir doch "aktiviert" in die Usertable einbauen....

**Comment by leona-ya** [comment]
wofür, wenn der vorgang fehlschlägt bin ich einfach noch in der alten schule drin
