### ISSUE TITLE
Farben auf den Übersichtsseiten werden nicht korrekt dargestellt

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#83]
Auf den Übersichtsseiten werden die Farben für Grundschulen und Gymnasien korrekt dargestellt (grün und blau), alles andere ist grau, obwohl die richtigen Schulform-IDs vergeben sind...

Achtung: neue Schulform-IDs (bereits in der Datenbank und im View geändert)

**Comment by leona-ya** [comment]
Mit anderen farben:
1: light-green
2: indigo
4: pink darken-4
5: teal
7: blue
anderes: grey
Farben: http://materializecss.com/color.html
