### ISSUE TITLE
Bestätigung für Neugenerierung des Schulcodes

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#86]
Vielleicht kann man da was schönes zaubern, so einen Toast fände ich ganz schön

**Comment by leona-ya** [comment]
Also was möchtest du:
- Eine Bestätigung wie 'Möchtest du das wirklich machen'
- oder ein Toast mit 'Der Schulcode wurde geändert.'

**Comment by jeriox** [comment]
Einen Toast mit 'Der Schulcode wurde geändert.', da man ja auf die selbe Seite zurückgeleitet wird.
