### ISSUE TITLE
View: Schulverwaltung

### ISSUE THREAD

**Issue by jeriox** [Schul-O-Mat/Schul-O-Mat#88]
Auf der Schulverwaltungsseite fehlen noch
- [x] die Darstellung des Schulcodes
- [x] die Auswahl der aktivierten Fragen
- [x] Opt-In für Zusendung des Schulcodes
- [x] Eintragen der Mailadresse für den Schulcode (vmtl in Schuldaten ändern)

**Comment by leona-ya** [comment]
funktion/beschreibung: #45
